# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=200)),
                ('comment_email', models.EmailField(max_length=254)),
                ('comment_homeurl', models.CharField(max_length=200, null=True)),
                ('comment_text', models.TextField()),
                ('comment_date', models.DateTimeField()),
                ('comment_rating', models.IntegerField()),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
