# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_isparent',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
