# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_comment_comment_isparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_homeurl',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
