# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20170402_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Parent',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_parentid',
            field=models.IntegerField(null=True),
        ),
    ]
