# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20170402_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_parentid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
